// Comprehensive country list — ISO 3166-1 alpha-2 codes
// Sorted alphabetically by label
// Includes UK nations separately (England, Scotland, Wales, Northern Ireland) for football context
export const COUNTRIES = [
  { code: 'AF', flag: '🇦🇫', label: 'Afghanistan' },
  { code: 'AL', flag: '🇦🇱', label: 'Albania' },
  { code: 'DZ', flag: '🇩🇿', label: 'Algeria' },
  { code: 'AD', flag: '🇦🇩', label: 'Andorra' },
  { code: 'AO', flag: '🇦🇴', label: 'Angola' },
  { code: 'AG', flag: '🇦🇬', label: 'Antigua and Barbuda' },
  { code: 'AR', flag: '🇦🇷', label: 'Argentina' },
  { code: 'AM', flag: '🇦🇲', label: 'Armenia' },
  { code: 'AU', flag: '🇦🇺', label: 'Australia' },
  { code: 'AT', flag: '🇦🇹', label: 'Austria' },
  { code: 'AZ', flag: '🇦🇿', label: 'Azerbaijan' },
  { code: 'BS', flag: '🇧🇸', label: 'Bahamas' },
  { code: 'BH', flag: '🇧🇭', label: 'Bahrain' },
  { code: 'BD', flag: '🇧🇩', label: 'Bangladesh' },
  { code: 'BB', flag: '🇧🇧', label: 'Barbados' },
  { code: 'BY', flag: '🇧🇾', label: 'Belarus' },
  { code: 'BE', flag: '🇧🇪', label: 'Belgium' },
  { code: 'BZ', flag: '🇧🇿', label: 'Belize' },
  { code: 'BJ', flag: '🇧🇯', label: 'Benin' },
  { code: 'BT', flag: '🇧🇹', label: 'Bhutan' },
  { code: 'BO', flag: '🇧🇴', label: 'Bolivia' },
  { code: 'BA', flag: '🇧🇦', label: 'Bosnia and Herzegovina' },
  { code: 'BW', flag: '🇧🇼', label: 'Botswana' },
  { code: 'BR', flag: '🇧🇷', label: 'Brazil' },
  { code: 'BN', flag: '🇧🇳', label: 'Brunei' },
  { code: 'BG', flag: '🇧🇬', label: 'Bulgaria' },
  { code: 'BF', flag: '🇧🇫', label: 'Burkina Faso' },
  { code: 'BI', flag: '🇧🇮', label: 'Burundi' },
  { code: 'CV', flag: '🇨🇻', label: 'Cabo Verde' },
  { code: 'KH', flag: '🇰🇭', label: 'Cambodia' },
  { code: 'CM', flag: '🇨🇲', label: 'Cameroon' },
  { code: 'CA', flag: '🇨🇦', label: 'Canada' },
  { code: 'CF', flag: '🇨🇫', label: 'Central African Republic' },
  { code: 'TD', flag: '🇹🇩', label: 'Chad' },
  { code: 'CL', flag: '🇨🇱', label: 'Chile' },
  { code: 'CN', flag: '🇨🇳', label: 'China' },
  { code: 'CO', flag: '🇨🇴', label: 'Colombia' },
  { code: 'KM', flag: '🇰🇲', label: 'Comoros' },
  { code: 'CG', flag: '🇨🇬', label: 'Congo' },
  { code: 'CR', flag: '🇨🇷', label: 'Costa Rica' },
  { code: 'HR', flag: '🇭🇷', label: 'Croatia' },
  { code: 'CU', flag: '🇨🇺', label: 'Cuba' },
  { code: 'CY', flag: '🇨🇾', label: 'Cyprus' },
  { code: 'CZ', flag: '🇨🇿', label: 'Czechia' },
  { code: 'DK', flag: '🇩🇰', label: 'Denmark' },
  { code: 'DJ', flag: '🇩🇯', label: 'Djibouti' },
  { code: 'DM', flag: '🇩🇲', label: 'Dominica' },
  { code: 'DO', flag: '🇩🇴', label: 'Dominican Republic' },
  { code: 'EC', flag: '🇪🇨', label: 'Ecuador' },
  { code: 'EG', flag: '🇪🇬', label: 'Egypt' },
  { code: 'SV', flag: '🇸🇻', label: 'El Salvador' },
  { code: 'GB-ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', label: 'England' },
  { code: 'GQ', flag: '🇬🇶', label: 'Equatorial Guinea' },
  { code: 'ER', flag: '🇪🇷', label: 'Eritrea' },
  { code: 'EE', flag: '🇪🇪', label: 'Estonia' },
  { code: 'SZ', flag: '🇸🇿', label: 'Eswatini' },
  { code: 'ET', flag: '🇪🇹', label: 'Ethiopia' },
  { code: 'FJ', flag: '🇫🇯', label: 'Fiji' },
  { code: 'FI', flag: '🇫🇮', label: 'Finland' },
  { code: 'FR', flag: '🇫🇷', label: 'France' },
  { code: 'GA', flag: '🇬🇦', label: 'Gabon' },
  { code: 'GM', flag: '🇬🇲', label: 'Gambia' },
  { code: 'GE', flag: '🇬🇪', label: 'Georgia' },
  { code: 'DE', flag: '🇩🇪', label: 'Germany' },
  { code: 'GH', flag: '🇬🇭', label: 'Ghana' },
  { code: 'GR', flag: '🇬🇷', label: 'Greece' },
  { code: 'GD', flag: '🇬🇩', label: 'Grenada' },
  { code: 'GT', flag: '🇬🇹', label: 'Guatemala' },
  { code: 'GN', flag: '🇬🇳', label: 'Guinea' },
  { code: 'GW', flag: '🇬🇼', label: 'Guinea-Bissau' },
  { code: 'GY', flag: '🇬🇾', label: 'Guyana' },
  { code: 'HT', flag: '🇭🇹', label: 'Haiti' },
  { code: 'HN', flag: '🇭🇳', label: 'Honduras' },
  { code: 'HU', flag: '🇭🇺', label: 'Hungary' },
  { code: 'IS', flag: '🇮🇸', label: 'Iceland' },
  { code: 'IN', flag: '🇮🇳', label: 'India' },
  { code: 'ID', flag: '🇮🇩', label: 'Indonesia' },
  { code: 'IR', flag: '🇮🇷', label: 'Iran' },
  { code: 'IQ', flag: '🇮🇶', label: 'Iraq' },
  { code: 'IE', flag: '🇮🇪', label: 'Ireland' },
  { code: 'IL', flag: '🇮🇱', label: 'Israel' },
  { code: 'IT', flag: '🇮🇹', label: 'Italy' },
  { code: 'CI', flag: '🇨🇮', label: 'Ivory Coast' },
  { code: 'JM', flag: '🇯🇲', label: 'Jamaica' },
  { code: 'JP', flag: '🇯🇵', label: 'Japan' },
  { code: 'JO', flag: '🇯🇴', label: 'Jordan' },
  { code: 'KZ', flag: '🇰🇿', label: 'Kazakhstan' },
  { code: 'KE', flag: '🇰🇪', label: 'Kenya' },
  { code: 'KI', flag: '🇰🇮', label: 'Kiribati' },
  { code: 'KW', flag: '🇰🇼', label: 'Kuwait' },
  { code: 'KG', flag: '🇰🇬', label: 'Kyrgyzstan' },
  { code: 'LA', flag: '🇱🇦', label: 'Laos' },
  { code: 'LV', flag: '🇱🇻', label: 'Latvia' },
  { code: 'LB', flag: '🇱🇧', label: 'Lebanon' },
  { code: 'LS', flag: '🇱🇸', label: 'Lesotho' },
  { code: 'LR', flag: '🇱🇷', label: 'Liberia' },
  { code: 'LY', flag: '🇱🇾', label: 'Libya' },
  { code: 'LI', flag: '🇱🇮', label: 'Liechtenstein' },
  { code: 'LT', flag: '🇱🇹', label: 'Lithuania' },
  { code: 'LU', flag: '🇱🇺', label: 'Luxembourg' },
  { code: 'MG', flag: '🇲🇬', label: 'Madagascar' },
  { code: 'MW', flag: '🇲🇼', label: 'Malawi' },
  { code: 'MY', flag: '🇲🇾', label: 'Malaysia' },
  { code: 'MV', flag: '🇲🇻', label: 'Maldives' },
  { code: 'ML', flag: '🇲🇱', label: 'Mali' },
  { code: 'MT', flag: '🇲🇹', label: 'Malta' },
  { code: 'MH', flag: '🇲🇭', label: 'Marshall Islands' },
  { code: 'MR', flag: '🇲🇷', label: 'Mauritania' },
  { code: 'MU', flag: '🇲🇺', label: 'Mauritius' },
  { code: 'MX', flag: '🇲🇽', label: 'Mexico' },
  { code: 'FM', flag: '🇫🇲', label: 'Micronesia' },
  { code: 'MD', flag: '🇲🇩', label: 'Moldova' },
  { code: 'MC', flag: '🇲🇨', label: 'Monaco' },
  { code: 'MN', flag: '🇲🇳', label: 'Mongolia' },
  { code: 'ME', flag: '🇲🇪', label: 'Montenegro' },
  { code: 'MA', flag: '🇲🇦', label: 'Morocco' },
  { code: 'MZ', flag: '🇲🇿', label: 'Mozambique' },
  { code: 'MM', flag: '🇲🇲', label: 'Myanmar' },
  { code: 'NA', flag: '🇳🇦', label: 'Namibia' },
  { code: 'NR', flag: '🇳🇷', label: 'Nauru' },
  { code: 'NP', flag: '🇳🇵', label: 'Nepal' },
  { code: 'NL', flag: '🇳🇱', label: 'Netherlands' },
  { code: 'NZ', flag: '🇳🇿', label: 'New Zealand' },
  { code: 'NI', flag: '🇳🇮', label: 'Nicaragua' },
  { code: 'NE', flag: '🇳🇪', label: 'Niger' },
  { code: 'NG', flag: '🇳🇬', label: 'Nigeria' },
  { code: 'KP', flag: '🇰🇵', label: 'North Korea' },
  { code: 'MK', flag: '🇲🇰', label: 'North Macedonia' },
  { code: 'GB-NIR', flag: '🇬🇧', label: 'Northern Ireland' },
  { code: 'NO', flag: '🇳🇴', label: 'Norway' },
  { code: 'OM', flag: '🇴🇲', label: 'Oman' },
  { code: 'PK', flag: '🇵🇰', label: 'Pakistan' },
  { code: 'PW', flag: '🇵🇼', label: 'Palau' },
  { code: 'PS', flag: '🇵🇸', label: 'Palestine' },
  { code: 'PA', flag: '🇵🇦', label: 'Panama' },
  { code: 'PG', flag: '🇵🇬', label: 'Papua New Guinea' },
  { code: 'PY', flag: '🇵🇾', label: 'Paraguay' },
  { code: 'PE', flag: '🇵🇪', label: 'Peru' },
  { code: 'PH', flag: '🇵🇭', label: 'Philippines' },
  { code: 'PL', flag: '🇵🇱', label: 'Poland' },
  { code: 'PT', flag: '🇵🇹', label: 'Portugal' },
  { code: 'QA', flag: '🇶🇦', label: 'Qatar' },
  { code: 'RO', flag: '🇷🇴', label: 'Romania' },
  { code: 'RU', flag: '🇷🇺', label: 'Russia' },
  { code: 'RW', flag: '🇷🇼', label: 'Rwanda' },
  { code: 'KN', flag: '🇰🇳', label: 'Saint Kitts and Nevis' },
  { code: 'LC', flag: '🇱🇨', label: 'Saint Lucia' },
  { code: 'VC', flag: '🇻🇨', label: 'Saint Vincent and the Grenadines' },
  { code: 'WS', flag: '🇼🇸', label: 'Samoa' },
  { code: 'SM', flag: '🇸🇲', label: 'San Marino' },
  { code: 'ST', flag: '🇸🇹', label: 'Sao Tome and Principe' },
  { code: 'SA', flag: '🇸🇦', label: 'Saudi Arabia' },
  { code: 'GB-SCT', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', label: 'Scotland' },
  { code: 'SN', flag: '🇸🇳', label: 'Senegal' },
  { code: 'RS', flag: '🇷🇸', label: 'Serbia' },
  { code: 'SC', flag: '🇸🇨', label: 'Seychelles' },
  { code: 'SL', flag: '🇸🇱', label: 'Sierra Leone' },
  { code: 'SG', flag: '🇸🇬', label: 'Singapore' },
  { code: 'SK', flag: '🇸🇰', label: 'Slovakia' },
  { code: 'SI', flag: '🇸🇮', label: 'Slovenia' },
  { code: 'SB', flag: '🇸🇧', label: 'Solomon Islands' },
  { code: 'SO', flag: '🇸🇴', label: 'Somalia' },
  { code: 'ZA', flag: '🇿🇦', label: 'South Africa' },
  { code: 'KR', flag: '🇰🇷', label: 'South Korea' },
  { code: 'SS', flag: '🇸🇸', label: 'South Sudan' },
  { code: 'ES', flag: '🇪🇸', label: 'Spain' },
  { code: 'LK', flag: '🇱🇰', label: 'Sri Lanka' },
  { code: 'SD', flag: '🇸🇩', label: 'Sudan' },
  { code: 'SR', flag: '🇸🇷', label: 'Suriname' },
  { code: 'SE', flag: '🇸🇪', label: 'Sweden' },
  { code: 'CH', flag: '🇨🇭', label: 'Switzerland' },
  { code: 'SY', flag: '🇸🇾', label: 'Syria' },
  { code: 'TW', flag: '🇹🇼', label: 'Taiwan' },
  { code: 'TJ', flag: '🇹🇯', label: 'Tajikistan' },
  { code: 'TZ', flag: '🇹🇿', label: 'Tanzania' },
  { code: 'TH', flag: '🇹🇭', label: 'Thailand' },
  { code: 'TL', flag: '🇹🇱', label: 'Timor-Leste' },
  { code: 'TG', flag: '🇹🇬', label: 'Togo' },
  { code: 'TO', flag: '🇹🇴', label: 'Tonga' },
  { code: 'TT', flag: '🇹🇹', label: 'Trinidad and Tobago' },
  { code: 'TN', flag: '🇹🇳', label: 'Tunisia' },
  { code: 'TR', flag: '🇹🇷', label: 'Turkey' },
  { code: 'TM', flag: '🇹🇲', label: 'Turkmenistan' },
  { code: 'TV', flag: '🇹🇻', label: 'Tuvalu' },
  { code: 'UG', flag: '🇺🇬', label: 'Uganda' },
  { code: 'UA', flag: '🇺🇦', label: 'Ukraine' },
  { code: 'AE', flag: '🇦🇪', label: 'United Arab Emirates' },
  { code: 'GB', flag: '🇬🇧', label: 'United Kingdom' },
  { code: 'US', flag: '🇺🇸', label: 'United States' },
  { code: 'UY', flag: '🇺🇾', label: 'Uruguay' },
  { code: 'UZ', flag: '🇺🇿', label: 'Uzbekistan' },
  { code: 'VU', flag: '🇻🇺', label: 'Vanuatu' },
  { code: 'VA', flag: '🇻🇦', label: 'Vatican City' },
  { code: 'VE', flag: '🇻🇪', label: 'Venezuela' },
  { code: 'VN', flag: '🇻🇳', label: 'Vietnam' },
  { code: 'GB-WLS', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', label: 'Wales' },
  { code: 'YE', flag: '🇾🇪', label: 'Yemen' },
  { code: 'ZM', flag: '🇿🇲', label: 'Zambia' },
  { code: 'ZW', flag: '🇿🇼', label: 'Zimbabwe' },
  { code: 'OTHER', flag: '🌍', label: 'Other' },
];
